// fetching diner info
export const GET_DINER_SUCCESS = 'GET_DINER_SUCCESS';
export const GET_DINER_FAILURE = 'GET_DINER_FAILURE';
export const GET_DINER_LOADING = 'GET_DINER_LOADING';

// fetching single truck
export const GET_DINER_SINGLE_TRUCK_SUCCESS = 'GET_DINER_SINGLE_TRUCK_SUCCESS';
export const GET_DINER_SINGLE_TRUCK_FAILURE = 'GET_DINER_SINGLE_TRUCK_FAILURE';
export const GET_DINER_SINGLE_TRUCK_LOADING = 'GET_DINER_SINGLE_TRUCK_LOADING';

// fetching all the trucks
export const GET_DINER_ALL_TRUCK_SUCCESS = 'GET_DINER_ALL_TRUCK_SUCCESS';
export const GET_DINER_ALL_TRUCK_FAILURE = 'GET_DINER_ALL_TRUCK_FAILURE';
export const GET_DINER_ALL_TRUCK_LOADING = 'GET_DINER_ALL_TRUCK_LOADING';

// adding favorite truck
export const POST_FAVORITE_SUCCESS = 'POST_FAVORITE_SUCCESS';
export const POST_FAVORITE_FAILURE = 'POST_FAVORITE_FAILURE';
export const POST_FAVORITE_LOADING = 'POST_FAVORITE_LOADING';

// delete favorite truck
export const DELETE_FAVORITE_SUCCESS = 'DELETE_FAVORITE_SUCCESS';
export const DELETE_FAVORITE_FAILURE = 'DELETE_FAVORITE_FAILURE';
export const DELETE_FAVORITE_LOADING = 'DELETE_FAVORITE_LOADING';

// adding customer rating
export const POST_RATING_SUCCESS = 'POST_RATING_SUCCESS';
export const POST_RATING_FAILURE = 'POST_RATING_FAILURE';
export const POST_RATING_LOADING = 'POST_RATING_LOADING';

// put rating
export const PUT_RATING_LOADING = 'PUT_RATING_LOADING';
export const PUT_RATING_SUCCESS = 'PUT_RATING_SUCCESS';
export const PUT_RATING_FAILURE = 'PUT_RATING_FAILURE';

// delete rating
export const DELETE_RATING_LOADING = 'DELETE_RATING_LOADING';
export const DELETE_RATING_SUCCESS = 'DELETE_RATING_SUCCESS';
export const DELETE_RATING_FAILURE = 'DELETE_RATING_FAILURE';

// get cuisineTypes
export const GET_CUISINE_TYPE_LOADING = 'GET_CUISINE_TYPES_LOADING';
export const GET_CUISINE_TYPE_SUCCESS = 'GET_CUISINE_TYPES_SUCCESS';
export const GET_CUISINE_TYPE_FAILURE = 'GET_CUISINE_TYPES_FAILURE';
